# Generated by Django 3.0.1 on 2019-12-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Новая заметка', max_length=200),
        ),
    ]
